name: article_generation_t5
channels:
  - defaults
dependencies:
  - python=3.8
  - pip
  - pip:
    - transformers==4.11.3
    - torch==1.10.0
    - pandas==1.3.4
    - fastapi
    - uvicorn
    - deepspeed
    - argparse
